extends: substitution
message: Consider using '%s' instead of '%s'
level: warning
ignorecase: false
# swap maps tokens in form of bad: good
# for more information: https://vale.sh/docs/topics/styles/#substitution
swap:
  '[A|a]pi': API
  typescript: Typescript
  ts: Typescript
  TS: Typescript
