name: 'Pro plan: support ❔'
description: As a Pro plan user, I need support with MUI X.
title: "[question] "
labels: ['status: needs triage', 'pro plan', 'question']
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        ⚠️ **Don't use this form if the problem is a bug or a feature request, use the dedicated form instead.**

        Thanks for contributing by creating an issue! ❤️
  - type: input
    id: contact
    attributes:
      label: Order ID 💳
      description: The order ID of the purchased Pro plan. Community users can [learn more about support](https://mui.com/getting-started/support/) in the documentation.
      placeholder: 'ex. #11111'
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Duplicates
      description: Please [search the history](https://github.com/mui-org/material-ui-x/issues) to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true
  - type: textarea
    attributes:
      label: Summary 💡
  - type: textarea
    attributes:
      label: The problem in depth 🔍
  - type: textarea
    attributes:
      label: Steps to reproduce 🕹
      description: |
        Provide a link to a live example (you can use codesandbox.io) and an unambiguous set of steps to reproduce this bug.
        Include code to reproduce, if relevant (which it most likely is).

        You can use the official codesandbox template of the [DataGrid](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) or [DataGridPro](https://codesandbox.io/s/datagridpro-v5-quick-start-5pjhc) as a starting point.

        If you have an issue concerning TypeScript please start from this TypeScript playground: https://mui.com/r/ts-issue-template.

        Issues that we can't reproduce will be closed.
      value: |
        Steps:

        1.
        2.
        3.
        4.
  - type: textarea
    attributes:
      label: Context 🔦
      description: What are you trying to accomplish? How has this issue affected you? Providing context helps us come up with a solution that is more useful in the real world.
  - type: textarea
    attributes:
      label: Your environment 🌎
      description: Run `npx @mui/envinfo` and post the results. If you encounter issues with TypeScript please include the used tsconfig.
      value: |
        <details>
          <summary>`npx @mui/envinfo`</summary>

        ```
          Don't forget to mention which browser you used.
          Output from `npx @mui/envinfo` goes here.
        ```
        </details>
