name: Add comment
on:
  issues:
    types:
      - closed
jobs:
  add-comment:
    if: github.event.issue.state_reason !== 'inactivity'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            :warning: This issue has been closed.
            If you have a similar problem, please open a [new issue](https://github.com/mui/mui-x/issues/new/choose) and provide details about your specific problem.
            If you can provide additional information related to this topic that could help future readers, please feel free to leave a comment.
            ${{ !['MEMBER', 'OWNER'].includes(github.event.issue.author_association) ? '
            **How did we do @${{ github.event.issue.user.login }}?**
            Your experience with our support team matters to us. If you have a moment, please share your thoughts through our [brief survey](https://tally.so/r/w4r5Mk?issue=${{ github.event.issue.number }}).' || '' }}
