name: Benchmarks

on:
  push:
    branches:
      - 'master'
      - 'next'
    paths:
      - 'packages/x-charts*/**'
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened
    branches:
      - 'master'
      - 'next'

jobs:
  benchmarks:
    name: Benchmarks Charts
    runs-on: ubuntu-latest
    # Only run the benchmarks for pull requests with the label 'component: charts'
    # Or for pushes to the master or next branch
    if: "${{ github.event_name == 'push' ||  contains(github.event.pull_request.labels.*.name, 'component: charts') }}"
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          run_install: false
      - name: Use Node.js 20.x
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          cache: 'pnpm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: pnpm install --frozen-lockfile
      # Ensure we are running on the prod version of our libs
      # Only charts and license are needed for the benchmarks
      - run: pnpm --filter @mui/x-license build
      - run: pnpm --filter @mui/x-charts build
      - run: pnpm --filter @mui/x-charts-pro build
      - name: Run benchmarks
        uses: CodSpeedHQ/action@a58b84c0b61569a9cbb7cfb378cc849d65cf1ce5
        with:
          run: pnpm test:performance:charts
          token: ${{ secrets.CODSPEED_TOKEN }}
