name: Discord Release Announcement

on:
  release:
    types: [ prereleased, published ]

jobs:
  delimiter-test:
    runs-on: ubuntu-latest
    name: Send message to discord
    steps:
      - name: parse and send message
        uses: michelengelen/discord-message-action@e5f378aae752589a3d6bc7f595a47e273e398aaa
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: MUI Releases
          separator: '<!--/ DO_NOT_REMOVE /-->'
