name: Order ID validation

on:
  issues:
    types: [opened]

jobs:
  validate-order-id:
    runs-on: ubuntu-latest
    name: Label issue based on order ID
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Label issue
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: |
            const script = require('./scripts/orderIdValidation.js')
            await script({core, github, context})
        env:
          ORDER_API_TOKEN: ${{ secrets.SHOP_AUTH_TOKEN }}
